import React from 'react'

export const NoMatch = () => (
  <div>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
    <p>Nomatch</p>
  </div>
)